# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests

on:
  push:

jobs:
  issues:
    runs-on: ubuntu-latest
    container:
      image: evanchooly/github-actions
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Configure the job
        run: |
          rm -vf testing-github.properties
          cp /mnt/files/testing-github.properties .
          mkdir -p ~/.m2
          cp /mnt/files/settings.xml ~/.m2/
          pwd
      - name: Build with Maven
        run: mvn -B deploy
