name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  pull-request:
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    secrets:
      GH_OAUTH: ${{ secrets.TESTING_GH_OAUTH }}
